### ISSUE TITLE
[BUG] Tableau ETL assumes report id length

### ISSUE THREAD

**Issue by paysni** [atlas-bi/atlas-bi-library-etl#22]
-   [x] I'm on the [latest version](https://github.com/atlas-bi/atlas-bi-library-etl/)
-   [x] I've searched the [issues](https://github.com/atlas-bi/atlas-bi-library-etl/issues)
-   [x] I've read the [docs](https://www.atlas.bi/docs/bi-library/etl)

## System Info

-   Browser: e.g. IE 11
-   OS: e.g. Windows 95

## Issue

in the Tableau Hierarchy step it assumes the report ID length is only up to 4 digits. This breaks when report ID length is greater than 4.

Snippet of code:
`ChildReportObjectBizKey =concat(
N'eptblp01','||'
, N'tableau'
,   '||'
,  N'Tableau Dashboard'
,   '||'
,   '||'
,   '||'
, case
	when LEN(h.childid)=5 then RIGHT(h.ChildID,1)
	when LEN(h.childid)=6 then right(h.ChildID,2)
	when LEN(h.childid)=7 then right (h.ChildID,3)
	else right(h.ChildID,4)
end
) `

This would fix it:
`ChildReportObjectBizKey =concat(
N'eptblp01','||'
, N'tableau'
,   '||'
,  N'Tableau Dashboard'
,   '||'
,   '||'
,   '||'
, SUBSTRING(h.ChildID,PATINDEX('%[0-9]%',h.ChildID),30)
) `

**Comment by christopherpickering** [comment]
Thanks @paysni!


![](https://media.tenor.com/Bv5ZxP2J8W4AAAAd/snoop-dogg-yep.gif)
